language: node_js
node_js:
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wordpress-theme' ]; then cd .. && eval "mv $currentfolder generator-wordpress-theme" && cd generator-wordpress-theme; fi
